apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-echo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "http-echo.name" . }}
    helm.sh/chart: {{ include "http-echo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "http-echo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
